---
name: Bug Report
description: Report a problem you encountered
title: '[Bug]: '
labels: ['bug']
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened? What did you expect?
      placeholder: Clear and concise description of the bug
    validations:
      required: true

  - type: input
    attributes:
      label: Environment
      description: Browser and version
      placeholder: e.g., Chrome 131, Edge 131
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Select text on a webpage
        2. Click the FlowReader icon
        3. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: Drag and drop or paste images here (optional)
      placeholder: Add screenshots if helpful

  - type: textarea
    attributes:
      label: Console Errors
      description: Open browser console (F12) and copy errors (optional)
      placeholder: Paste error messages here...
      render: shell

  - type: dropdown
    attributes:
      label: LLM Provider (optional)
      description: Which LLM provider are you using?
      options:
        - Zhipu AI
        - OpenAI
        - Qwen
        - Custom API
