---
name: General Question
description: Ask a question or start a discussion
title: ''
labels: ['question']
body:
  - type: textarea
    attributes:
      label: Question / Discussion
      description: What would you like to ask or discuss?
      placeholder: Please describe your question or topic in detail
    validations:
      required: true

  - type: textarea
    attributes:
      label: Context
      description: Any additional context or relevant information
      placeholder: What have you tried? What documentation have you read?
